name: main

on:
  push:
    branches:
      - feature_1
  workflow_dispatch:

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/feature_1'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python version: 3.12
          
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks bundle - dev
        env:
          DATABRICKS_HOST: ${{ secrets.DEV_BAKEHOUSE_WS }}
          DATABRICKS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
        run: |
          databricks workspace import-dir /Workspace/Users/jeevanprabhakaran19@gmail.com/TnKingmaker2026 --overwrite

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python version: 3.12
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks bundle - prod
        env:
          DATABRICKS_HOST: ${{ secrets.DEV_BAKEHOUSE_WS }}
          DATABRICKS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
        run: |
          databricks workspace import-dir /Workspace/Users/jeevanprabhakaran19@gmail.com/Prod_TnKingmaker2026 --overwrite
