name: Deploy Notebook to Prod

on:
  push:
    branches:
      - feature_1  # Triggers when code is pushed/merged to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy Notebook
        env:
          DATABRICKS_HOST: ${{ secrets.DEV_BAKEHOUSE_WS }}
          DATABRICKS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
        run: |
          databricks workspace import ./Notebook.ipynb /Workspace/Users/jeevanprabhakaran19@gmail.com/TnKingmaker2026 --language PYTHON --overwrite
